
server:
  port: 9191

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: USER-AUTH-SERVICE
          uri: lb://USER-AUTH-SERVICE
          predicates:
            - Path=/USER-AUTH-SERVICE/**
        - id: PAYMENT-ALIPAY-SERVICE
          uri: lb://PAYMENT-ALIPAY-SERVICE
          predicates:
            - Path=/PAYMENT-ALIPAY-SERVICE/**
        - id: PAYMENT-PAYPAL-SERVICE
          uri: lb://PAYMENT-PAYPAL-SERVICE
          predicates:
            - Path=/PAYMENT-PAYPAL-SERVICE/**
        - id: PAYMENT-STRIPE-SERVICE
          uri: lb://PAYMENT-STRIPE-SERVICE
          predicates:
            - Path=/PAYMENT-STRIPE-SERVICE/**
        - id: PRODUCT-SERVICE
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/PRODUCT-SERVICE/**
        - id: SALES-ORDER-SERVICE
          uri: lb://SALES-ORDER-SERVICE
          predicates:
            - Path=/SALES-ORDER-SERVICE/**
#        - id: SUPPLIER-SERVICE
#          uri: lb://SUPPLIER-SERVICE
#          predicates:
#            - Path=/SUPPLIER-SERVICE/**

